name: Docker Image CI

on:
  create:
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        repository: motey/arkserver
        tags: latest
        tag_with_ref: true
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PW }}
